image: wmacmillan/gp-general-dev


ports:
- port: 8050
  onOpen: ignore
- port: 8051
  onOpen: ignore
- port: 8888
  onOpen: ignore

tasks:
- command: pip install shortuuid matplotlib python-igraph streamlit quandl yfinance pytest FinQuant && nohup jupyter notebook --config=/workspace/special-system/.jupyter/jupyter_notebook_config.py &


github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: false
    addBadge: true

vscode:
  extensions:
    - ms-python.python
    - njpwerner.autodocstring
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - jeandeaual.noir
